name: Deploy Laravel Sail with phpMyAdmin

on:
  push:
    branches: [master]

env:
  DB_PORT: 3306
  PMA_PORT: 8080

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.EC2_HOST }} ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI..." >> ~/.ssh/known_hosts

      - name: Deploy Application
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'ENDSSH'
          #!/bin/bash
          set -ex

          # 1. System setup
          sudo dnf update -y
          sudo dnf install -y git docker docker-compose-plugin
          sudo systemctl enable --now docker
          sudo usermod -aG docker $USER
          newgrp docker <<< $(groups)

          # 2. Application setup
          [ ! -d ~/app ] && git clone ${{ github.repository_url }} ~/app
          cd ~/app
          git pull origin master

          # 3. Configure environment
          cat > .env <<EOL
          APP_NAME=Laravel
          APP_ENV=production
          APP_KEY=
          APP_DEBUG=false
          APP_URL=http://${{ secrets.EC2_HOST }}

          DB_CONNECTION=mysql
          DB_HOST=mysql
          DB_PORT=$DB_PORT
          DB_DATABASE=laravel
          DB_USERNAME=root
          DB_PASSWORD=

          PMA_PORT=$PMA_PORT
          EOL

          # 4. Generate app key if missing
          grep -q '^APP_KEY=$' .env && \
            docker run --rm -v $(pwd):/app -w /app php:8.2-cli php artisan key:generate

          # 5. Start containers
          docker compose up -d --build

          # 6. Database setup
          docker compose exec laravel.test php artisan migrate --force
          docker compose exec laravel.test php artisan optimize:clear

          echo "Application: http://${{ secrets.EC2_HOST }}"
          echo "phpMyAdmin: http://${{ secrets.EC2_HOST }}:$PMA_PORT"
          ENDSSH
