version: '3.8'

services:
  laravel.test:
    build:
      context: ./vendor/laravel/sail/runtimes/8.2
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP:-1000}'
    image: sail-8.2/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - target: 80
        published: ${APP_PORT:-80}
        protocol: tcp
        mode: host
      - target: ${VITE_PORT:-5173}
        published: ${VITE_PORT:-5173}
        protocol: tcp
        mode: host
    environment:
      WWWUSER: '${WWWUSER:-1000}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    volumes:
      - type: bind
        source: .
        target: /var/www/html
    networks:
      sail:
        aliases:
          - laravel.test
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - target: 3306
        published: ${FORWARD_DB_PORT:-3306}
        protocol: tcp
        mode: host
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - type: volume
        source: sail-mysql
        target: /var/lib/mysql
      - type: bind
        source: ./vendor/laravel/sail/database/mysql/create-testing-database.sh
        target: /docker-entrypoint-initdb.d/10-create-testing-database.sh
    networks:
      - sail
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    networks:
      - sail
    depends_on:
      mysql:
        condition: service_healthy

networks:
  sail:
    driver: bridge

volumes:
  sail-mysql:
    driver: local
