version: '3.8'

services:
  laravel.test:
    build:
      context: ./vendor/laravel/sail/runtimes/8.2
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP:-1000}'
    image: sail-8.2/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    expose:
      - "80"
    environment:
      WWWUSER: '${WWWUSER:-1000}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    volumes:
      - type: bind
        source: .
        target: /var/www/html
    networks:
      sail:
        aliases:
          - laravel.test
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    image: nginx:latest
    container_name: sail-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - certbot-ssl:/etc/letsencrypt
    depends_on:
      - laravel.test
    networks:
      - sail

  certbot:
    image: certbot/certbot
    container_name: sail-certbot
    volumes:
      - certbot-ssl:/etc/letsencrypt
      - ./nginx/conf.d:/etc/nginx/conf.d
    entrypoint: "/bin/sh -c"
    command: >
      "certbot certonly --standalone
       --preferred-challenges http
       --agree-tos
       --no-eff-email
       --email hokshmax1@gmail.com
       -d ec2-16-24-105-243.me-south-1.compute.amazonaws.com"

  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - target: 3306
        published: ${FORWARD_DB_PORT:-3306}
        protocol: tcp
        mode: host
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - type: volume
        source: sail-mysql
        target: /var/lib/mysql
      - type: bind
        source: ./vendor/laravel/sail/database/mysql/create-testing-database.sh
        target: /docker-entrypoint-initdb.d/10-create-testing-database.sh
    networks:
      - sail
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    networks:
      - sail
    depends_on:
      - mysql

networks:
  sail:
    driver: bridge

volumes:
  sail-mysql:
    driver: local
  certbot-ssl:
    driver: local
