name: Deploy Laravel Sail with phpMyAdmin

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy and Start Services
        run: |
          ssh -o BatchMode=yes ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'ENDSSH'
          #!/bin/bash
          set -ex

          # 1. System setup
          sudo dnf update -y
          sudo dnf install -y git docker docker-compose-plugin
          sudo systemctl enable --now docker
          sudo usermod -aG docker $USER
          newgrp docker <<< $(groups)

          # 2. Application setup
          [ ! -d ~/app ] && git clone https://github.com/hokshmaxx/RaheeqWeb-new_asal.git ~/app
          cd ~/app
          git pull origin master

          # 3. Ensure Sail permissions
          chmod +x vendor/bin/sail

          # 4. Start containers (force rebuild if needed)
          ./vendor/bin/sail down || true
          ./vendor/bin/sail build --no-cache
          ./vendor/bin/sail up -d

          # 5. Verify services are running
          timeout 60 bash -c 'until docker compose ps | grep "running"; do sleep 5; done' || \
            (echo "Containers failed to start"; exit 1)

          # 6. Database setup
          ./vendor/bin/sail artisan migrate --force
          ./vendor/bin/sail artisan optimize:clear

          # 7. Verify Sail is operational
          curl -sSf http://localhost > /dev/null || \
            (echo "Application failed to start"; exit 1)

          echo "Deployment successful!"
          echo "App: http://${{ secrets.EC2_HOST }}"
          echo "phpMyAdmin: http://${{ secrets.EC2_HOST }}:8081"
          ENDSSH
