name: Deploy Laravel Sail to EC2 (AL2023)

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH (without ssh-keyscan, disables strict host checking)
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa
          sed -i 's/\\n/\n/g' $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          ssh-keygen -y -f $HOME/.ssh/id_rsa > /dev/null

          # To enable strict host key checking, uncomment below and
          # add your EC2 host fingerprint to secrets as EC2_SSH_HOST_KEY
          # echo "${{ secrets.EC2_SSH_HOST_KEY }}" >> $HOME/.ssh/known_hosts

      - name: Deploy Application
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o BatchMode=yes ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -ex

            # 1. Update system and install core dependencies
            sudo dnf update -y
            sudo dnf install -y git docker
            sudo dnf install -y mariadb-connector-c  # MySQL client library

            # 2. Configure Docker
            sudo systemctl enable --now docker
            sudo usermod -aG docker $USER
            newgrp docker  # Refresh group permissions

            # 3. Set up application directory
            if [ ! -d ~/raheeq ]; then
              git clone https://github.com/hokshmaxx/RaheeqWeb-new_asal.git ~/raheeq
              cd ~/raheeq
              cp .env.example .env
            else
              cd ~/raheeq
              git fetch origin
              git reset --hard origin/master
            fi

            # 4. Install PHP dependencies via Docker
            docker run --rm \
              -v $(pwd):/opt \
              -w /opt \
              laravelsail/php82-composer:latest \
              composer install --ignore-platform-reqs --no-interaction

            # 5. Configure environment (example)
            echo "APP_ENV=production" >> .env
            echo "APP_DEBUG=false" >> .env

            # 6. Start Laravel Sail
            ./vendor/bin/sail down || true
            ./vendor/bin/sail up -d --build

            # 7. Run database migrations
            ./vendor/bin/sail artisan migrate --force
            ./vendor/bin/sail artisan optimize:clear

            echo "Deployment completed successfully"
          EOF
