name: Deploy Laravel Sail to EC2

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          # Fix formatting and ensure proper key structure
          sed -i 's/\\n/\n/g' ~/.ssh/id_rsa
          echo "" >> ~/.ssh/id_rsa  # Ensure final newline
          chmod 600 ~/.ssh/id_rsa
          # Verify key
          ssh-keygen -y -f ~/.ssh/id_rsa > /dev/null
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Install dependencies and deploy
        run: |
          ssh -o BatchMode=yes ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e  # Exit immediately if any command fails
            echo "=== Starting Deployment ==="

            # 1. Install required system packages
            echo "Installing system dependencies..."
            sudo yum update -y
            sudo yum install -y git docker
            sudo amazon-linux-extras install -y epel

            # 2. Configure Docker
            echo "Setting up Docker..."
            sudo systemctl enable docker
            sudo systemctl start docker
            sudo usermod -aG docker $USER

            # 3. Clone or update repository
            echo "Setting up application directory..."
            if [ ! -d ~/raheeq ]; then
              git clone https://github.com/hokshmaxx/RaheeqWeb-new_asal.git ~/raheeq
              cd ~/raheeq
              cp .env.example .env
            else
              cd ~/raheeq
              git fetch origin
              git reset --hard origin/master
            fi

            # 4. Install PHP dependencies using Dockerized Composer
            echo "Installing PHP dependencies..."
            docker run --rm \
              -v $(pwd):/opt \
              -w /opt \
              laravelsail/php82-composer:latest \
              composer install --ignore-platform-reqs --no-interaction --prefer-dist

            # 5. Set up environment variables (if needed)
            echo "DB_HOST=mysql" >> .env
            echo "DB_DATABASE=${DB_DATABASE}" >> .env
            echo "DB_USERNAME=${DB_USERNAME}" >> .env
            echo "DB_PASSWORD=${DB_PASSWORD}" >> .env

            # 6. Start Laravel Sail
            echo "Starting Laravel Sail..."
            ./vendor/bin/sail down || true
            ./vendor/bin/sail up -d --build

            # 7. Run database migrations
            echo "Running migrations..."
            ./vendor/bin/sail artisan migrate --force

            # 8. Optimize application
            echo "Optimizing application..."
            ./vendor/bin/sail artisan optimize:clear
            ./vendor/bin/sail artisan view:cache
            ./vendor/bin/sail artisan route:cache

            echo "=== Deployment Complete ==="
          EOF
