name: Deploy Laravel Sail to EC2

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          # Fix line endings and permissions
          sed -i 's/\\n/\n/g' ~/.ssh/id_rsa
          echo "" >> ~/.ssh/id_rsa  # Ensure final newline
          chmod 600 ~/.ssh/id_rsa
          # Verify key format
          ssh-keygen -y -f ~/.ssh/id_rsa > /dev/null
          ssh-keyscan -H 15.185.55.55 >> ~/.ssh/known_hosts

      - name: Test connection
        run: ssh -o BatchMode=yes ec2-user@15.185.55.55 echo "SSH connection successful"

      - name: Deploy application
        run: |
          ssh -o BatchMode=yes ec2-user@15.185.55.55 << 'EOF'
            cd ~/raheeq || git clone https://github.com/hokshmaxx/RaheeqWeb-new_asal.git ~/raheeq
            cd ~/raheeq
            git pull origin master

            # Ensure Docker is running
            sudo systemctl start docker

            # Start Laravel Sail
            ./vendor/bin/sail down || true
            ./vendor/bin/sail up -d --build

            # Run migrations
            ./vendor/bin/sail artisan migrate --force
          EOF
